### ISSUE TITLE
Potentially missing assertions in Hand.java

### ISSUE THREAD

**Issue by AllanWang** [prmr/SoftwareDesign#17]
[`contains`](https://github.com/prmr/SoftwareDesign/blob/master/modules/answers/Hand.java#L80)

Given that we are not allowing removals of `null`, shouldn't we also prohibit querying null cards?

[comparisons](https://github.com/prmr/SoftwareDesign/blob/master/modules/answers/Hand.java#L90)

Is it worth having null assertions for all the comparisons? This is namely to replace NPEs with assertion exceptions.

**Comment by prmr** [comment]
`contains`: it would make sense, although not strictly necessary, since in this particular case `List.contains(null)` does the right thing and predictable returns false. However, I agree that eliminating `null` from legal inputs using DbC would make the overall design clearer, so I will change this.

**Comment by prmr** [comment]
`comparisons`: It's a good observation that the handling of `null` arguments is not elegant here. Unfortunately there is no good solution due to the lax specification of the interface and the dubious choice of an NPE as an explicit part of the interface. Use of DBC here may introduce a different kind of design flaw, namely a violation of the Liskov Substitutability Principle, something covered in Module 6. I will try to expand the exercises to cover this situation.
